services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartstock
    ports:
      - "5433:5432"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/smartstock
      SECRET_KEY: supersecretkey
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend